-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.action_log
(
    log_id serial NOT NULL,
    ticker character varying(20) COLLATE pg_catalog."default" NOT NULL,
    log_timestamp timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    trigger_type character varying(50) COLLATE pg_catalog."default",
    trigger_content text COLLATE pg_catalog."default",
    ai_analysis text COLLATE pg_catalog."default",
    is_read boolean DEFAULT false,
    CONSTRAINT action_log_pkey PRIMARY KEY (log_id)
);

CREATE TABLE IF NOT EXISTS public.daily_stock_data
(
    ticker character varying(20) COLLATE pg_catalog."default" NOT NULL,
    trade_date date NOT NULL,
    open_price numeric(12, 2),
    high_price numeric(12, 2),
    low_price numeric(12, 2),
    close_price numeric(12, 2),
    volume bigint,
    CONSTRAINT daily_stock_data_pkey PRIMARY KEY (ticker, trade_date)
);

CREATE TABLE IF NOT EXISTS public.daily_todos
(
    id serial NOT NULL,
    task_date date NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    ticker character varying(16) COLLATE pg_catalog."default",
    priority text COLLATE pg_catalog."default" NOT NULL DEFAULT 'medium'::text,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::text,
    sort_order integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    completed_at timestamp with time zone,
    CONSTRAINT daily_todos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.historical_earnings
(
    earnings_id serial NOT NULL,
    ticker character varying(20) COLLATE pg_catalog."default" NOT NULL,
    period character varying(20) COLLATE pg_catalog."default" NOT NULL,
    heps numeric(10, 2) NOT NULL,
    notes text COLLATE pg_catalog."default",
    results_date date NOT NULL,
    CONSTRAINT historical_earnings_pkey PRIMARY KEY (earnings_id),
    CONSTRAINT historical_earnings_ticker_period_key UNIQUE (ticker, period)
);

CREATE TABLE IF NOT EXISTS public.ignored_events
(
    ignored_event_id serial NOT NULL,
    ticker character varying(20) COLLATE pg_catalog."default" NOT NULL,
    event_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    event_date date NOT NULL,
    date_ignored timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ignored_events_pkey PRIMARY KEY (ignored_event_id),
    CONSTRAINT ignored_events_ticker_event_type_event_date_key UNIQUE (ticker, event_type, event_date)
);

CREATE TABLE IF NOT EXISTS public.portfolio_holdings
(
    id serial NOT NULL,
    portfolio_id integer,
    ticker character varying(20) COLLATE pg_catalog."default" NOT NULL,
    quantity numeric(15, 4) NOT NULL,
    average_buy_price numeric(15, 2) NOT NULL,
    last_updated timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT portfolio_holdings_pkey PRIMARY KEY (id),
    CONSTRAINT portfolio_holdings_portfolio_id_ticker_key UNIQUE (portfolio_id, ticker)
);

CREATE TABLE IF NOT EXISTS public.portfolio_transactions
(
    id serial NOT NULL,
    portfolio_id integer,
    ticker character varying(20) COLLATE pg_catalog."default" NOT NULL,
    transaction_type character varying(10) COLLATE pg_catalog."default" NOT NULL,
    quantity numeric(15, 4) NOT NULL,
    price numeric(15, 2) NOT NULL,
    transaction_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fees numeric(15, 2) DEFAULT 0.0,
    notes text COLLATE pg_catalog."default",
    CONSTRAINT portfolio_transactions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.portfolios
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT portfolios_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.price_hit_log
(
    hit_id serial NOT NULL,
    ticker character varying(10) COLLATE pg_catalog."default" NOT NULL,
    price_level numeric NOT NULL,
    hit_timestamp timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT price_hit_log_pkey PRIMARY KEY (hit_id)
);

CREATE TABLE IF NOT EXISTS public.price_update_log
(
    log_id serial NOT NULL,
    update_timestamp timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    records_saved integer,
    CONSTRAINT price_update_log_pkey PRIMARY KEY (log_id)
);

CREATE TABLE IF NOT EXISTS public.raw_stock_valuations
(
    id bigserial NOT NULL,
    ticker character varying(20) COLLATE pg_catalog."default" NOT NULL,
    results_period_end date NOT NULL,
    results_period_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    heps_12m_zarc numeric(18, 4),
    dividend_12m_zarc numeric(18, 4),
    cash_gen_ps_zarc numeric(18, 4),
    nav_ps_zarc numeric(18, 4),
    quick_ratio numeric(18, 6),
    source character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'sharedata'::character varying,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    results_release_date date,
    period_months integer,
    CONSTRAINT raw_stock_valuations_pkey PRIMARY KEY (id),
    CONSTRAINT raw_stock_valuations_ticker_period_uniq UNIQUE (ticker, results_period_end)
);

COMMENT ON TABLE public.raw_stock_valuations
    IS 'Historical fundamental data for multiple periods per ticker, scraped from ShareData';

COMMENT ON COLUMN public.raw_stock_valuations.results_period_end
    IS 'End date of the financial period (e.g., 2025-03-31 for Mar 2025)';

COMMENT ON COLUMN public.raw_stock_valuations.results_period_label
    IS 'Full human-readable period label from ShareData (e.g., "Mar 2025 Final (12m) 23 Jun 2025")';

COMMENT ON COLUMN public.raw_stock_valuations.heps_12m_zarc
    IS '12 Month HEPS in ZAR cents';

COMMENT ON COLUMN public.raw_stock_valuations.dividend_12m_zarc
    IS '12 Month Dividend in ZAR cents';

COMMENT ON COLUMN public.raw_stock_valuations.cash_gen_ps_zarc
    IS 'Cash Generated Per Share in ZAR cents';

COMMENT ON COLUMN public.raw_stock_valuations.nav_ps_zarc
    IS 'Net Asset Value Per Share in ZAR cents';

COMMENT ON COLUMN public.raw_stock_valuations.quick_ratio
    IS 'Quick Ratio (may be NULL for some sectors/periods)';

CREATE TABLE IF NOT EXISTS public.sens
(
    sens_id serial NOT NULL,
    ticker character varying(20) COLLATE pg_catalog."default" NOT NULL,
    publication_datetime timestamp with time zone NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sens_pkey PRIMARY KEY (sens_id)
);

CREATE TABLE IF NOT EXISTS public.stock_analysis
(
    analysis_id serial NOT NULL,
    ticker character varying(20) COLLATE pg_catalog."default" NOT NULL,
    research text COLLATE pg_catalog."default",
    strategy text COLLATE pg_catalog."default",
    price_levels numeric(10, 2)[],
    deepresearch text COLLATE pg_catalog."default",
    deepresearch_date date,
    CONSTRAINT stock_analysis_pkey PRIMARY KEY (analysis_id),
    CONSTRAINT stock_analysis_ticker_key UNIQUE (ticker)
);

CREATE TABLE IF NOT EXISTS public.stock_details
(
    ticker character varying(20) COLLATE pg_catalog."default" NOT NULL,
    update_q1 date,
    update_q2 date,
    update_q3 date,
    update_q4 date,
    earnings_q1 date,
    earnings_q2 date,
    earnings_q3 date,
    earnings_q4 date,
    market_cap bigint,
    exchange_name character varying(50) COLLATE pg_catalog."default",
    priority character varying(10) COLLATE pg_catalog."default",
    full_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT financial_report_dates_pkey PRIMARY KEY (ticker)
);

CREATE TABLE IF NOT EXISTS public.stock_price_levels
(
    level_id serial NOT NULL,
    ticker character varying(20) COLLATE pg_catalog."default" NOT NULL,
    price_level numeric(12, 2),
    level_type character varying(50) COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    date_added date DEFAULT CURRENT_DATE,
    is_ignored_on_scan boolean DEFAULT false,
    CONSTRAINT stock_price_levels_pkey PRIMARY KEY (level_id),
    CONSTRAINT uq_ticker_price UNIQUE (ticker, price_level)
);

CREATE TABLE IF NOT EXISTS public.watchlist
(
    watchlist_id serial NOT NULL,
    ticker character varying(20) COLLATE pg_catalog."default" NOT NULL,
    target_price numeric(12, 2),
    entry_price numeric(12, 2),
    stop_loss numeric(12, 2),
    reward_risk_ratio numeric(10, 2),
    date_added date DEFAULT CURRENT_DATE,
    notes text COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'Pending'::character varying,
    is_long boolean DEFAULT true,
    CONSTRAINT watchlist_pkey PRIMARY KEY (watchlist_id)
);

ALTER TABLE IF EXISTS public.action_log
    ADD CONSTRAINT action_log_ticker_fkey FOREIGN KEY (ticker)
    REFERENCES public.stock_details (ticker) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.daily_stock_data
    ADD CONSTRAINT daily_stock_data_ticker_fkey FOREIGN KEY (ticker)
    REFERENCES public.stock_details (ticker) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.historical_earnings
    ADD CONSTRAINT historical_earnings_ticker_fkey FOREIGN KEY (ticker)
    REFERENCES public.stock_details (ticker) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_historical_earnings_ticker
    ON public.historical_earnings(ticker);


ALTER TABLE IF EXISTS public.ignored_events
    ADD CONSTRAINT ignored_events_ticker_fkey FOREIGN KEY (ticker)
    REFERENCES public.stock_details (ticker) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.portfolio_holdings
    ADD CONSTRAINT portfolio_holdings_portfolio_id_fkey FOREIGN KEY (portfolio_id)
    REFERENCES public.portfolios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.portfolio_holdings
    ADD CONSTRAINT portfolio_holdings_ticker_fkey FOREIGN KEY (ticker)
    REFERENCES public.stock_details (ticker) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.portfolio_transactions
    ADD CONSTRAINT portfolio_transactions_portfolio_id_fkey FOREIGN KEY (portfolio_id)
    REFERENCES public.portfolios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.portfolio_transactions
    ADD CONSTRAINT portfolio_transactions_ticker_fkey FOREIGN KEY (ticker)
    REFERENCES public.stock_details (ticker) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.price_hit_log
    ADD CONSTRAINT price_hit_log_ticker_fkey FOREIGN KEY (ticker)
    REFERENCES public.stock_details (ticker) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.raw_stock_valuations
    ADD CONSTRAINT raw_stock_valuations_ticker_fk FOREIGN KEY (ticker)
    REFERENCES public.stock_details (ticker) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS raw_stock_valuations_ticker_idx
    ON public.raw_stock_valuations(ticker);


ALTER TABLE IF EXISTS public.sens
    ADD CONSTRAINT sens_ticker_fkey FOREIGN KEY (ticker)
    REFERENCES public.stock_details (ticker) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.stock_analysis
    ADD CONSTRAINT stock_analysis_ticker_fkey FOREIGN KEY (ticker)
    REFERENCES public.stock_details (ticker) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS stock_analysis_ticker_key
    ON public.stock_analysis(ticker);


ALTER TABLE IF EXISTS public.stock_price_levels
    ADD CONSTRAINT stock_price_levels_ticker_fkey FOREIGN KEY (ticker)
    REFERENCES public.stock_details (ticker) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS stock_price_levels_ticker_idx
    ON public.stock_price_levels(ticker);


ALTER TABLE IF EXISTS public.watchlist
    ADD CONSTRAINT watchlist_ticker_fkey FOREIGN KEY (ticker)
    REFERENCES public.stock_details (ticker) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS watchlist_ticker_idx
    ON public.watchlist(ticker);

END;